const programs=[
 {n:'01',title:'Traditional Medicare',tag:'ACO REACH · LEAD · MSSP',text:'Support complete documentation, proactive gap closure and coordinated care across ACO REACH, LEAD and MSSP fee-for-service populations.'},
 {n:'02',title:'Medicare Advantage',text:'Bring risk, quality and coding priorities into the encounter to support stronger plan and provider performance.'},
 {n:'03',title:'Medicaid Managed Care',text:'Help managed Medicaid plans and their network providers close quality and risk gaps while coordinating care for enrolled members.'},
];
const companion=[
 ['Ambient listening','Uses AI to listen to the encounter and generate a clinical summary note, without pulling the provider away from the patient.'],
 ['RAF recapture','Surfaces supported risk-adjustment (RAF) recapture opportunities at the point of care.'],
 ['Gap closure','Guides the provider toward open care and quality actions during the visit.'],
 ['ICD & CPT support','AI-suggested ICD and CPT coding, always left for clinician review and confirmation.'],
 ['MEAT alignment','Prompts for complete, defensible documentation — Monitor, Evaluate, Assess and Treat — in the encounter.'],
 ['Real-time write-back','Returns reviewed documentation, codes and actions directly to the EHR.'],
];
const command=[
 ['Retrospective analytics','See unresolved issues, trends and performance across populations, providers and contracts.'],
 ['Issue identification','Find the recapture, quality, coding and scheduling opportunities that need attention.'],
 ['Work management','Assign, prioritize and follow opportunities from identification through closure.'],
 ['Scheduling assistance','Bring the right patients back at the right time based on clinical and value-based priorities.'],
];
export default function Home(){return <main>
 <section className="hero shell" id="top"><div className="tag"><i/> Encounter intelligence for value-based care</div><h1>Close more opportunities.<br/><em>During the encounter.</em></h1><div className="hero-foot"><div className="hero-copy"><p>Vediq gives primary care teams AI-assisted guidance for supported documentation, risk and quality opportunities—while keeping clinicians in control.</p><div className="hero-actions"><a className="button dark" href="/demo">Request a demo <b>↗</b></a><a className="text-link" href="#system">See how it works ↓</a></div></div></div></section>
 <section className="proof-band"><div className="shell proof-grid"><strong>Already deployed in a real primary care workflow.</strong><p>Built with direct feedback from the clinicians and staff who use it in day-to-day care.</p><a href="/demo">See Vediq in action ↗</a></div></section>
 <section className="dark-band"><div className="shell band-grid"><p>One closed loop from population insight to completed action.</p><div><span>01</span><strong>Identify</strong><small>Command center</small></div><div><span>02</span><strong>Close</strong><small>Clinical Companion</small></div><div><span>03</span><strong>Improve</strong><small>Value-based performance</small></div></div></section>
 <section className="section shell" id="system"><div className="intro"><span>How Vediq works</span><h2>Two connected products.<br/>One performance loop.</h2><p>The command center is a retrospective, population-health-style analytics and work-management view for ACO, plan and practice leaders. The Companion is an ambient, AI-listening assistant that runs during the encounter itself, guiding completion and writing the result back to the EHR.</p></div><div className="loop"><article><b>01</b><small>Command center</small><h3>See what needs attention.</h3><p>Retrospective analytics surface issues across the population and help teams prioritize the work.</p></article><i>→</i><article className="accent"><b>02</b><small>Companion</small><h3>Resolve it at the encounter.</h3><p>Ambient intelligence guides the provider through recapture, gap closure, coding and documentation.</p></article><i>→</i><article><b>03</b><small>EHR + command center</small><h3>Complete the record.</h3><p>Clinician-reviewed data returns to the EHR in real time and updates the management view.</p></article></div></section>
 <section className="blue section" id="companion"><div className="shell"><div className="intro light"><span>Point-of-care Companion</span><h2>Close the opportunity<br/>while care is happening.</h2><p>Vediq runs alongside the encounter, giving providers timely guidance without turning the visit into another administrative workflow. It listens, drafts the note, and surfaces supported recapture, quality and coding opportunities for clinician review. Nothing is finalized without the provider&apos;s confirmation.</p></div><div className="feature-grid">{companion.map((x,i)=><article key={x[0]}><span>0{i+1}</span><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</div><div className="section-cta light-cta"><p>See how the Companion fits into a real primary care encounter.</p><a className="button lime" href="/demo">Request a demo <b>↗</b></a></div></div></section>
 <section className="section shell" id="command"><div className="intro"><span>Management command center</span><h2>Find the issues.<br/>Manage the work.</h2><p>A retrospective operating view for ACO, plan and provider leaders to understand performance, coordinate action and prepare future encounters. In practice: leadership sees a prioritized list of open issues, assigns and tracks them by practice or provider, and knows the moment they're resolved at the next encounter. Built on EHR and payer claims data live today, with HIE and ADT feed integration already built in and ready to connect as new sources come online.</p></div><div className="command-grid">{command.map((x,i)=><article key={x[0]}><span>0{i+1}</span><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</div></section>
 <section className="ink section" id="programs"><div className="shell"><div className="intro light"><span>Programs supported</span><h2>Built for the Medicare<br/>value-based landscape.</h2><p>Vediq supports providers, ACOs and managed care organizations across three core value-based environments, adapting encounter guidance and management priorities to the work that matters in each.</p></div><div className="program-grid">{programs.map(p=><article key={p.n}><span>{p.n}</span><h3>{p.title}</h3>{p.tag&&<small>{p.tag}</small>}<p>{p.text}</p></article>)}</div></div></section>
 <section className="section shell audience"><div className="intro"><span>Who Vediq serves</span><h2>One workflow.<br/>Three clear outcomes.</h2></div><div className="audience-grid three"><article><small>Primary care providers</small><h3>Stay focused on the patient.</h3><p>Receive timely guidance, review the result and complete the record without duplicate work.</p></article><article><small>Practice leadership</small><h3>Turn opportunities into action.</h3><p>Give care teams a practical way to address supported risk and quality priorities during the visit.</p></article><article><small>ACOs &amp; care organizations</small><h3>Connect insight to closure.</h3><p>Coordinate priorities across practices and understand whether opportunities are resolved.</p></article></div></section>
 <section className="deployment section"><div className="shell deployment-grid"><div><span>Deployed in primary care</span><h2>Built in the workflow.<br/>Not around it.</h2></div><div><p>Vediq is already deployed with select primary care providers participating in an Accountable Care Organization (ACO), giving our team direct insight into how encounter intelligence must work in day-to-day clinical care.</p><p>We work with primary care practices, ACOs and value-based care organizations looking to close more risk and quality opportunities during the encounter.</p><a className="button dark" href="/demo">Explore Vediq for your organization <b>↗</b></a></div></div></section>
 <section className="section shell" id="who-we-are"><div className="who-grid"><div><span>Who we are</span><h2>Built from inside<br/>value-based care.</h2></div><div className="who-copy"><p>Vediq was created by a team with deep experience in healthcare data, analytics, technology and value-based care. We saw a persistent gap: organizations can identify risk and quality opportunities across their populations, but too many of those opportunities are still missed when the patient is actually in front of the provider.</p><p><strong>Vediq was built to close that gap.</strong></p><p>We connect population-level intelligence with the clinical encounter—helping providers act on supported risk, quality, documentation and coding opportunities while care is happening.</p><p>Vediq is being built and deployed with primary care providers participating in value-based care, giving our team direct feedback from the people who use it in real clinical workflows.</p><p><strong>Our goal is simple: turn value-based care insight into action at the point where it matters most—the patient encounter.</strong></p></div></div></section>
 <section className="closing shell"><span>See Vediq in action</span><h2>Bring your workflow.<br/><em>We&apos;ll show the fit.</em></h2><div><p>Get a focused walkthrough of the Vediq Companion and Command Center, and discuss how they could support your EHR and value-based care workflow.</p><a className="button lime" href="/demo">Request a demo <b>↗</b></a></div></section>
 </main>}
